version: "3"
services:
  backend:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && pdm run instart"
    ports:
      - 8000:8000
    depends_on:
      - mysql
      - neo4j
  mysql:
    image: mysql:5.7.16
    ports:
    - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: library
      MYSQL_USER: library
      MYSQL_PASSWORD: 3203
      TZ: Asia/Shanghai
  neo4j:
    image: neo4j:5.2
    environment:
      - NEO4J_AUTH=neo4j/3203
      - dbms.connectors.default_listen_address=0.0.0.0
      - dbms.connector.bolt.listen_address=0.0.0.0:7687
      - dbms.connector.http.listen_address=0.0.0.0:7474
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./data/neo4j/data:/data
      - ./data/neo4j/logs:/logs
      - ./data/neo4j/conf:/conf
